# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shadowsocks_pyqt5.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(731, 452)
        self.button_copy = QtWidgets.QPushButton(Form)
        self.button_copy.setGeometry(QtCore.QRect(20, 410, 80, 21))
        self.button_copy.setObjectName("button_copy")
        self.button_add = QtWidgets.QPushButton(Form)
        self.button_add.setGeometry(QtCore.QRect(20, 375, 80, 21))
        self.button_add.setObjectName("button_add")
        self.button_delete = QtWidgets.QPushButton(Form)
        self.button_delete.setGeometry(QtCore.QRect(106, 375, 80, 21))
        self.button_delete.setObjectName("button_delete")
        self.button_ok = QtWidgets.QPushButton(Form)
        self.button_ok.setGeometry(QtCore.QRect(280, 410, 71, 20))
        self.button_ok.setObjectName("button_ok")
        self.button_cancel = QtWidgets.QPushButton(Form)
        self.button_cancel.setGeometry(QtCore.QRect(370, 410, 71, 20))
        self.button_cancel.setObjectName("button_cancel")
        self.listWidget_server_list = QtWidgets.QListWidget(Form)
        self.listWidget_server_list.setGeometry(QtCore.QRect(20, 30, 181, 311))
        self.listWidget_server_list.setObjectName("listWidget_server_list")
        self.lineEdit_Proxy_port = QtWidgets.QLineEdit(Form)
        self.lineEdit_Proxy_port.setGeometry(QtCore.QRect(350, 370, 90, 19))
        self.lineEdit_Proxy_port.setObjectName("lineEdit_Proxy_port")
        self.groupBox_server_config = QtWidgets.QGroupBox(Form)
        self.groupBox_server_config.setGeometry(QtCore.QRect(220, 10, 221, 331))
        self.groupBox_server_config.setObjectName("groupBox_server_config")
        self.lineEdit_serverip = QtWidgets.QLineEdit(self.groupBox_server_config)
        self.lineEdit_serverip.setGeometry(QtCore.QRect(80, 50, 108, 29))
        self.lineEdit_serverip.setObjectName("lineEdit_serverip")
        self.label_7 = QtWidgets.QLabel(self.groupBox_server_config)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 64, 21))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_server_config)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 67, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox_server_config)
        self.lineEdit_password.setGeometry(QtCore.QRect(84, 130, 108, 29))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_4 = QtWidgets.QLabel(self.groupBox_server_config)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 67, 21))
        self.label_4.setObjectName("label_4")
        self.checkBox_show_password = QtWidgets.QCheckBox(self.groupBox_server_config)
        self.checkBox_show_password.setGeometry(QtCore.QRect(89, 169, 121, 27))
        self.checkBox_show_password.setObjectName("checkBox_show_password")
        self.label_5 = QtWidgets.QLabel(self.groupBox_server_config)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 68, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.groupBox_server_config)
        self.lineEdit_timeout.setGeometry(QtCore.QRect(83, 230, 108, 29))
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")
        self.comboBox_encryption = QtWidgets.QComboBox(self.groupBox_server_config)
        self.comboBox_encryption.setGeometry(QtCore.QRect(89, 199, 101, 21))
        self.comboBox_encryption.setObjectName("comboBox_encryption")
        self.comboBox_encryption.addItem("")
        self.comboBox_encryption.addItem("")
        self.comboBox_encryption.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_server_config)
        self.label_2.setGeometry(QtCore.QRect(9, 199, 71, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_server_port = QtWidgets.QLineEdit(self.groupBox_server_config)
        self.lineEdit_server_port.setGeometry(QtCore.QRect(83, 90, 108, 29))
        self.lineEdit_server_port.setObjectName("lineEdit_server_port")
        self.groupBox_settings = QtWidgets.QGroupBox(Form)
        self.groupBox_settings.setGeometry(QtCore.QRect(470, 10, 251, 331))
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.textEdit_socksproxy = QtWidgets.QTextEdit(self.groupBox_settings)
        self.textEdit_socksproxy.setGeometry(QtCore.QRect(120, 190, 111, 31))
        self.textEdit_socksproxy.setObjectName("textEdit_socksproxy")
        self.checkBox_acting_all_traffic = QtWidgets.QCheckBox(self.groupBox_settings)
        self.checkBox_acting_all_traffic.setGeometry(QtCore.QRect(190, 120, 21, 27))
        self.checkBox_acting_all_traffic.setText("")
        self.checkBox_acting_all_traffic.setObjectName("checkBox_acting_all_traffic")
        self.checkBox_enable_system_agent = QtWidgets.QCheckBox(self.groupBox_settings)
        self.checkBox_enable_system_agent.setGeometry(QtCore.QRect(190, 90, 21, 27))
        self.checkBox_enable_system_agent.setText("")
        self.checkBox_enable_system_agent.setObjectName("checkBox_enable_system_agent")
        self.textEdit_httpproxy = QtWidgets.QTextEdit(self.groupBox_settings)
        self.textEdit_httpproxy.setGeometry(QtCore.QRect(120, 150, 111, 31))
        self.textEdit_httpproxy.setObjectName("textEdit_httpproxy")
        self.label_9 = QtWidgets.QLabel(self.groupBox_settings)
        self.label_9.setGeometry(QtCore.QRect(18, 91, 141, 21))
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.groupBox_settings)
        self.label_15.setGeometry(QtCore.QRect(20, 160, 91, 21))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox_settings)
        self.label_14.setGeometry(QtCore.QRect(20, 120, 141, 21))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_settings)
        self.label_16.setGeometry(QtCore.QRect(20, 200, 91, 21))
        self.label_16.setObjectName("label_16")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(280, 370, 63, 19))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "shadowsocks_pyqt5"))
        self.button_copy.setText(_translate("Form", "copy"))
        self.button_add.setText(_translate("Form", "add"))
        self.button_delete.setText(_translate("Form", "delete"))
        self.button_ok.setText(_translate("Form", "OK"))
        self.button_cancel.setText(_translate("Form", "cancel"))
        self.groupBox_server_config.setTitle(_translate("Form", "server"))
        self.label_7.setText(_translate("Form", "server ip    "))
        self.label_6.setText(_translate("Form", "timeout(s) "))
        self.label_4.setText(_translate("Form", "server port"))
        self.checkBox_show_password.setText(_translate("Form", "show password"))
        self.label_5.setText(_translate("Form", "password   "))
        self.comboBox_encryption.setItemText(0, _translate("Form", "rc4-md5"))
        self.comboBox_encryption.setItemText(1, _translate("Form", "salas20"))
        self.comboBox_encryption.setItemText(2, _translate("Form", "chacha20"))
        self.label_2.setText(_translate("Form", "encryption"))
        self.groupBox_settings.setTitle(_translate("Form", "Settings"))
        self.textEdit_socksproxy.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2589</p></body></html>"))
        self.textEdit_httpproxy.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">127.0.0.1:2589</p></body></html>"))
        self.label_9.setText(_translate("Form", "Enable System Agent"))
        self.label_15.setText(_translate("Form", "HTTP(S) Proxy"))
        self.label_14.setText(_translate("Form", "Acting All Traffic"))
        self.label_16.setText(_translate("Form", "SOCKS   Proxy"))
        self.label_8.setText(_translate("Form", "Proxy port"))

